# Tensor creation and manipulation example using tensor libraries.


In [2]:
import tensorflow as tf
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])   ## tf.constant(value, shape=...)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [3]:
tensor.shape

TensorShape([2, 3])

In [4]:
scalar = tf.constant(7)            # RANK 0
vector = tf.constant([10, 10])     # RANK 1
matrix = tf.constant([[1, 2], [3, 4]])  # RANK 2
tensor_3d = tf.constant([[[1], [2]], [[3], [4]]])  # RANK 3

In [5]:
rank_scalar = tf.rank(scalar)
rank_vector = tf.rank(vector)   
rank_matrix = tf.rank(matrix)
rank_tensor_3d = tf.rank(tensor_3d)

print("Rank of scalar:", rank_scalar.numpy())
print("Rank of vector:", rank_vector.numpy())   
print("Rank of matrix:", rank_matrix.numpy())
print("Rank of 3D tensor:", rank_tensor_3d.numpy())


Rank of scalar: 0
Rank of vector: 1
Rank of matrix: 2
Rank of 3D tensor: 3


In [6]:
dim1_length = tensor.shape[0]  # Length of the first dimension (rows)
dim2_length = tensor.shape[1]  # Length of the second dimension (columns)

print("Length of dimension 1 (rows):", dim1_length)
print("Length of dimension 2 (columns):", dim2_length)

Length of dimension 1 (rows): 2
Length of dimension 2 (columns): 3


# Tensor Indexing

In [7]:
#Slicing Tensors
t1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9])
t1

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [8]:
s1 = tf.slice(t1, begin=[1], size=[3])  ## begin is the starting index, size is the number of elements to slice, only for 1D tensor
s2 = t1[1:4] ## alternative way to slice 1D tensor using Python slicing
print(s1)
print(s2)

tf.Tensor([2 3 4], shape=(3,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [10]:
# Slicing 2D Tensors
t2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(t2)
s3 = tf.slice(t2, begin=[0, 0], size=[2, 3])  ## Slicing a 2D tensor [2, 3] means 2 rows and 3 columns
s4 = t2[0:2, 0:2]  ## Alternative way to slice 2D tensor using Python slicing [start, end]
print('\nSecond row:\n', t2[1, :])
print(s3)
print(s4)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

Second row:
 tf.Tensor([4 5 6], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [ ]:
#Extracting specific rows and columns: TensorFlow lets you grab specific elements or chunks of your data,
# Meet tf.gather: 
t2 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
diagonals = t2[[0,0], [1,1], [2,2]]
print('\nDiagonals:\n', diagonals)

TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got [0, 0]